version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PYTHONUNBUFFERED=1 
    volumes:
      - .env:/app/.env


  ui:
    build:
      context: .
      dockerfile: UIDockerfile
    ports:
      - "9001:5173"
